return {
  modified = "",
  readonly = "󰦝",
  close = "󱎘",
  save = "󰆓",
  reload = "󰑐",
  noice = "󰒡",

  git_symbols = {
    added = "",
    modified = "",
    removed = "",
    copied = "",
    renamed = "",
    type_changed = "",
    unmerged = "",
    untracked = "",
    ignored = "",
  },

  diagnostics = {
    error = "󰅙",
    warn = "󰀦",
    info = "󰋼",
    hint = "󰌵",
  },

  separators = {
    left = "",
    right = "",
  },

  file = "󰝰",
  branch = "󰘬",
  lsp = "󰣖",
  location = "󰆤",
  progress = "󰏰",

  keymaps = "󰌌",
  projects = "󰉓",
  recent = "󱋡",
  new_file = "󰝒",
  find_file = "󰱼",
  find_config = "󱁻",
  find_text = "󱎸",
  git = "󰊢",
  lazy = "󰒲",
  quit = "󰈆",
  vault = "",
  bookmark_on = "󰃀",
  bookmark_off = "󰃃",
  code = "󰅩",
  hunk = "󰢪",
  change_base = "󱒒",
  trouble = "󰔫",
}
